[project]
name = "pblogs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "myst-parser>=4.0.1",
    "sphinx-copybutton>=0.5.2",
    "sphinx-markdown-tables>=0.0.17",
    "sphinx-rtd-theme>=3.0.2",
]
